name:                xno

dependencies:
- base >= 4.7 && < 5
- vector

library:
  source-dirs: src

ghc-options:
- -Wall
- -Werror

executables:
  xno-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xno

tests:
  xno-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xno
    - hspec
