name:                xno

dependencies:
- base >= 4.7 && < 5
- vector
- hspec

library:
  source-dirs: src

ghc-options:
- -Wall
- -Werror
- -O2

executables:
  xno-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    dependencies:
    - xno

tests:
  xno-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -rtsopts
    dependencies:
    - xno
